In [1]:
from numpy import nan
import  torch


tensor([[1., 2.],
        [3., nan],
        [nan, 4.]])

In [5]:
num = torch.tensor([[1.0, 2.0],
        [3.0, nan],
        [nan, 4.0]])

# num = num[~torch.isnan(num)]

In [6]:
# num

In [7]:
num.shape

torch.Size([3, 2])

In [8]:
num.nansum(dim=1)

tensor([3., 3., 4.])

In [10]:
rewards = torch.rand(10)

In [11]:
rewards

tensor([0.3967, 0.0370, 0.6209, 0.4503, 0.3194, 0.7444, 0.6329, 0.2296, 0.6127,
        0.9535])

In [13]:
rewards.view(-1, 5)

tensor([[0.3967, 0.0370, 0.6209, 0.4503, 0.3194],
        [0.7444, 0.6329, 0.2296, 0.6127, 0.9535]])

In [17]:
ones = torch.ones(5)

In [18]:
zeros = torch.zeros(5)

In [19]:
ones + zeros

tensor([1., 1., 1., 1., 1.])

In [33]:
concat = torch.concat([ones, zeros])

In [37]:
concat = concat.view(-1, 5)

In [42]:
concat

tensor([[1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0.]])

In [43]:
concat.shape

torch.Size([2, 5])

In [38]:
num_generations = 5

In [49]:
mean = concat.mean(dim=1)
mean

tensor([1., 0.])

In [47]:
mean.repeat_interleave(num_generations, dim=0)


tensor([1., 1., 1., 1., 1., 0., 0., 0., 0., 0.])

In [51]:
concat

tensor([[1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0.]])

In [53]:
std = concat.std(dim=1)
std

tensor([0., 0.])

In [54]:
std.repeat_interleave(num_generations, dim=0)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])