# 神经网络
- 神经网络包括输入层、隐藏层（中间层）、输出层
- 设计神经网络时，输入与输出层的神经元数量是固定的，中间层的层数以及神经元数量可以自由指定

### 示例
- 下图输入层有三个输入单元，中间层有一层、4个输入神经元，输出层有两个输出单元
- 箭头代表训练与测试时候的数据流向

![神经网络](images/神经网络.png)  

<br>

- 神经网络中输入层的数据经过每一个神经元的计算后就变成了输出值
- 神经网络的中间层数据越多，神经元数量越多，功能越强大，同时所需计算资源越大
- 例如，经典的AlexNet模型有8个中间层、65万个神经元、6000万个参数

![多层中间层神经网络](images/多层中间层神经网络.png)

## 神经元
- 每一个神经元包括：输入、输出、以及两个计算
    - x表示输入
    - w表示权值
        - w与相对应的x相乘
    - ∑ 表示求和
    - a是求和后的值
    - f是激活函数，把a得值转换到一个固定范围内
  
![神经元](images/神经元.png)

<br>

# Autograd包
- pytorch所有神经网络的核心，为tensor上的所有操作提供了自动区分
- 在autograd下，反向传递（backprop）代码自动定义
    - .require_grad
        - 在tensor上设定.require_grad=true后，autograd会自动追踪与该tensor有关的所有运算
    - .backward()
        - 所有运算完成后，执行.backward()，autograd会自动计算梯度并执行反向传递
    - .grad
        - 用来访问梯度
    - with torch.no_grad()
        - 自动忽略梯度

In [1]:
import torch

In [2]:
x = torch.ones(2, 2, requires_grad=True)
print(x)
print(x.shape)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
torch.Size([2, 2])


In [10]:
y = x+2
z = y*y+3
out = z.mean() # 计算张量z中所有元素的平均值，并返回一个标量

print('y:\n', y)
print('z:\n', z)
print('out:\n', out)

y:
 tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
z:
 tensor([[12., 12.],
        [12., 12.]], grad_fn=<AddBackward0>)
out:
 tensor(12., grad_fn=<MeanBackward0>)


In [8]:
out.backward()

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [6]:
print(x.grad)

tensor([[1.5000, 1.5000],
        [1.5000, 1.5000]])


In [7]:
with torch.no_grad():
    k=x+1
    print(k)

tensor([[2., 2.],
        [2., 2.]])
