In [1]:
import torch

In [4]:
tensor0d = torch.tensor(1)

tensor1d = torch.tensor([1, 2, 3])

tensor2d = torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor3d = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [5]:
tensor1d = torch.tensor([1, 2, 3])
tensor1d.dtype

torch.int64

In [10]:
floatvec = torch.tensor([1., 2., 3.])
floatvec.dtype

torch.float32

In [11]:
floatvec.to(torch.float16)

tensor([1., 2., 3.], dtype=torch.float16)

In [12]:
floatvec.data

tensor([1., 2., 3.])

In [13]:
floatvec.shape

torch.Size([3])

In [14]:
tensor0d.shape

torch.Size([])

In [15]:
tensor2d.shape

torch.Size([2, 3])

In [16]:
tensor2d.reshape(3,2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [17]:
tensor2d.reshape(6)

tensor([1, 2, 3, 4, 5, 6])

In [18]:
tensor2d.reshape(-1)

tensor([1, 2, 3, 4, 5, 6])

In [19]:
tensor2d.reshape(5)


RuntimeError: shape '[5]' is invalid for input of size 6

In [20]:
tensor2d.view(-1)

tensor([1, 2, 3, 4, 5, 6])

In [21]:
tensor2d.view(-1, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [23]:
tensor2d.shape

torch.Size([2, 3])

In [24]:
tensor2d.view(-1, 3)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [25]:
tensor2d.shape

torch.Size([2, 3])

In [26]:
tensor2d.view(-1)

tensor([1, 2, 3, 4, 5, 6])

In [27]:
tensor2d.T

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [28]:
tensor2d.view(-1)

tensor([1, 2, 3, 4, 5, 6])

In [29]:
tensor2d.shape

torch.Size([2, 3])

In [30]:
tensor2d.view(-1, 3)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [31]:
tensor2d.shape

torch.Size([2, 3])

In [32]:
tensor2d.view(-1, 0)

RuntimeError: shape '[-1, 0]' is invalid for input of size 6

In [33]:
tensor2d.view(-1, 1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [34]:
tensor2d.T

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [35]:
tensor2d

tensor([[1, 2, 3],
        [4, 5, 6]])

In [36]:
tensor2d.reshape(2, -1)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [37]:
tensor2d.matmul(tensor2d.T)

tensor([[14, 32],
        [32, 77]])

In [38]:
tensor2d @ tensor2d.T

tensor([[14, 32],
        [32, 77]])