In [78]:
import torch
import torch.nn.functional as F

class NeuralNetwork(torch.nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.linear1 = torch.nn.Linear(2, 2)
        self.linear2 = torch.nn.Linear(2, 1)
        
    def forward(self, x):
        x = self.linear1(x)
        x = F.relu(x)
        
        
        x = self.linear2(x)
        x = torch.sigmoid(x)
        return x
    
model = NeuralNetwork()
print(model)

NeuralNetwork(
  (linear1): Linear(in_features=2, out_features=2, bias=True)
  (linear2): Linear(in_features=2, out_features=1, bias=True)
)


In [31]:
y = torch.tensor([[1.0]], dtype=torch.float32)
x1 = torch.tensor([[1.0, 2.0]], dtype=torch.float32)

y.shape



torch.Size([1, 1])

In [32]:
logists = model(x1)
loss = F.binary_cross_entropy(logists, y)
print(loss)

tensor(0.4781, grad_fn=<BinaryCrossEntropyBackward0>)


In [33]:
from torch.autograd import grad
grad(loss, model.parameters(), retain_graph= True)

(tensor([[-0.2621, -0.5242],
         [ 0.0000,  0.0000]]),
 tensor([-0.2621,  0.0000]),
 tensor([[-0.0658,  0.0000]]),
 tensor([-0.3800]))

In [20]:
model.parameters()

<generator object Module.parameters at 0x000001EBA5A48510>

In [35]:
loss.backward()

In [83]:
class NeuralNetwork1(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.layers = torch.nn.Sequential(
            torch.nn.Linear(2, 2),
            torch.nn.ReLU(),
            torch.nn.Linear(2, 1),
            torch.nn.Sigmoid()
        )
        
    def forward(self, x):
        return self.layers(x)
        

In [40]:
model = NeuralNetwork1()

In [41]:
print(model)

NeuralNetwork1(
  (layers): Sequential(
    (0): Linear(in_features=2, out_features=2, bias=True)
    (1): ReLU()
    (2): Linear(in_features=2, out_features=1, bias=True)
    (3): Sigmoid()
  )
)


In [44]:
num_params = sum(p.numel() for p in model.parameters() if p.requires_grad)

In [45]:
num_params

9

In [46]:
for p in model.parameters():
    print(p.shape)

torch.Size([2, 2])
torch.Size([2])
torch.Size([1, 2])
torch.Size([1])


In [47]:
x1= torch.tensor([[1.0, 2.0]], dtype=torch.float32)
w1 = x1.T
b = torch.tensor([[1.0]], dtype=torch.float32)

y = w1 @ x1 + b

In [48]:
y

tensor([[2., 3.],
        [3., 5.]])

In [50]:
x1.shape, w1.shape, b.shape

(torch.Size([1, 2]), torch.Size([2, 1]), torch.Size([1, 1]))

In [54]:
(x1 @ w1).shape

torch.Size([1, 1])

In [52]:
b.shape

torch.Size([1, 1])

In [55]:
model

NeuralNetwork1(
  (layers): Sequential(
    (0): Linear(in_features=2, out_features=2, bias=True)
    (1): ReLU()
    (2): Linear(in_features=2, out_features=1, bias=True)
    (3): Sigmoid()
  )
)

In [58]:
model.layers[0].weight

Parameter containing:
tensor([[0.5089, 0.3155],
        [0.4378, 0.4179]], requires_grad=True)

In [59]:
model.layers

Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): ReLU()
  (2): Linear(in_features=2, out_features=1, bias=True)
  (3): Sigmoid()
)

In [60]:
model.parameters()

<generator object Module.parameters at 0x000001EBA5A4B840>

In [65]:
for p in model.parameters():
    print(p)

Parameter containing:
tensor([[0.5089, 0.3155],
        [0.4378, 0.4179]], requires_grad=True)
Parameter containing:
tensor([-0.5323,  0.1529], requires_grad=True)
Parameter containing:
tensor([[0.0424, 0.4891]], requires_grad=True)
Parameter containing:
tensor([-0.0456], requires_grad=True)


In [62]:
model.layers[0].weight

Parameter containing:
tensor([[0.5089, 0.3155],
        [0.4378, 0.4179]], requires_grad=True)

In [63]:
model.layers[0].bias

Parameter containing:
tensor([-0.5323,  0.1529], requires_grad=True)

In [72]:
model = NeuralNetwork()
model.layers[0].weight

Parameter containing:
tensor([[-0.2837, -0.3459],
        [-0.4991,  0.6979]], requires_grad=True)

In [76]:
torch.manual_seed(123)
model = NeuralNetwork()
print(model.layers[0].weight)

Parameter containing:
tensor([[-0.2883,  0.0234],
        [-0.3512,  0.2667]], requires_grad=True)


In [84]:
x1 = torch.tensor([[1.0, 2.0]], dtype=torch.float32)
output = model(x1)
print(output)

tensor([[0.6137]], grad_fn=<SigmoidBackward0>)


In [85]:
x1.shape

torch.Size([1, 2])

In [87]:
model

NeuralNetwork(
  (linear1): Linear(in_features=2, out_features=2, bias=True)
  (linear2): Linear(in_features=2, out_features=1, bias=True)
)

In [90]:
x1 = torch.tensor([[1.0, 2.0]], dtype=torch.float32)
output = model(x1)
print(output)

tensor([[0.6137]], grad_fn=<SigmoidBackward0>)


In [91]:
x1 = torch.tensor([[1.0, 2.0], [3.0, 4.0]], dtype=torch.float32)

In [92]:
x1.shape

torch.Size([2, 2])

In [93]:
model(x1)

tensor([[0.6137],
        [0.6137]], grad_fn=<SigmoidBackward0>)

In [101]:
x2 = torch.range(1.0, 8.0)
x2.shape

C:\Users\zhangchenchen\AppData\Local\Temp\ipykernel_12432\2007442638.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  x2 = torch.range(1.0, 8.0)


torch.Size([8])

In [99]:
x2

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [96]:
x2.view(2, 3)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [108]:
x2 = x2.view(2, 2, 2)

In [109]:
model(x2)

tensor([[[0.6137],
         [0.6137]],

        [[0.6137],
         [0.6137]]], grad_fn=<SigmoidBackward0>)

In [105]:
model

NeuralNetwork(
  (linear1): Linear(in_features=2, out_features=2, bias=True)
  (linear2): Linear(in_features=2, out_features=1, bias=True)
)

In [111]:
with torch.no_grad():
    out = model(x2)
out

tensor([[[0.6137],
         [0.6137]],

        [[0.6137],
         [0.6137]]])

In [113]:
with torch.no_grad():
    out = torch.softmax(model(x2), dim=1)
out

tensor([[[0.5000],
         [0.5000]],

        [[0.5000],
         [0.5000]]])